# Generated by Django 5.2.17 on 2026-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
